FROM ubuntu:22.04

LABEL org.opencontainers.image.source="https://github.com/jaredchurch/containers"
LABEL org.opencontainers.image.licenses="MIT"

ENV DEBIAN_FRONTEND=noninteractive
ARG PUID=1000
ARG PGID=1000

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ARG RUNNER_SHA256=4ef2f25285f0ae4477f1fe1e346db76d2f3ebf03824e2ddd1973a2819bf6c8cf
ARG RUNNER_DOWNLOAD_URL=https://github.com/actions/runner/releases/download/v2.335.1/actions-runner-linux-x64-2.335.1.tar.gz
ARG RUNNER_TGZ=/actions-runner/actions-runner.tar.gz

RUN ln -fs /usr/share/zoneinfo/Pacific/Auckland /etc/localtime \
    && echo "Pacific/Auckland" | tee /etc/timezone

# hadolint ignore=DL3008
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
	    jq \
        curl \
        libdigest-sha-perl \
        wget \
        apt-transport-https \
        software-properties-common \
        sudo \
        python3-full \
        pip && \
    rm -rf /var/lib/apt/lists/*

# hadolint ignore=DL3008
RUN install -d -m 0755 /etc/apt/keyrings && \
    wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null && \
    chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null && \
    apt-get update && \
    apt-get install -y --no-install-recommends gh && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /actions-runner && \
    wget -q -O ${RUNNER_TGZ} ${RUNNER_DOWNLOAD_URL} && \
    echo "${RUNNER_SHA256}  ${RUNNER_TGZ}" | shasum -a 256 -c && \
    tar xzf ${RUNNER_TGZ} -C /actions-runner && \
    rm -f ${RUNNER_TGZ}

WORKDIR /actions-runner

RUN ./bin/installdependencies.sh

RUN groupadd -g ${PGID} ubuntu && \
    useradd -l -u ${PUID} -g ubuntu -m -s /bin/bash ubuntu && \
    chown -R ubuntu:ubuntu /actions-runner && \
    echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# hadolint ignore=DL3008
RUN . /etc/os-release && \
    MS_PKG_URL="https://packages.microsoft.com/config/${ID}/${VERSION_ID}/packages-microsoft-prod.deb" && \
    wget -q "$MS_PKG_URL" && \
    dpkg -i packages-microsoft-prod.deb && \
    rm -f packages-microsoft-prod.deb && \
    apt-get update && \
    apt-get install -y --no-install-recommends powershell && \
    rm -rf /var/lib/apt/lists/*

COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER ${PUID}

HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
    CMD ["pgrep", "-f", "Runner.Listener"]

ENTRYPOINT ["/entrypoint.sh"]

### End of File
