FROM debian:bookworm-slim

LABEL org.opencontainers.image.source="https://github.com/jaredchurch/containers"
LABEL org.opencontainers.image.licenses="MIT"

# hadolint ignore=DL3008
RUN apt-get update && apt-get install -y --no-install-recommends \
    bind9 \
    dnsutils \
&& rm -rf /var/lib/apt/lists/*

HEALTHCHECK --interval=30s --timeout=5s --retries=3 --start-period=10s \
  CMD ["dig", "@localhost", ".", "SOA", "+norecurse"]

### End of File
