# Use the official Python 3.10 image built on Debian Trixie Slim
FROM python:3.10-slim-trixie

# Prevent Python from writing .pyc files to disk
ENV PYTHONDONTWRITEBYTECODE=1

# Prevent Python from buffering stdout and stderr
ENV PYTHONUNBUFFERED=1




### End of File
