name: Build and Push Custom Base Image

on:
  push:
    paths:
      - 'base-image/**'
      - '.github/workflows/build-base.yml'
  workflow_dispatch:
    inputs:
      dev_mode:
        description: 'Build as dev image only (dev tag) even on the main branch'
        required: false
        default: false
        type: boolean

jobs:
  build:
    uses: ./.github/workflows/_build-container-dev.yml
    with:
      image_name: base
      context: ./base-image
      dockerfile: ./base-image/Dockerfile.base
      dev_mode: ${{ inputs.dev_mode || false }}
    secrets: inherit
