name: Build and Push Airflow Image

on:
  push:
    paths:
      - 'airflow-image/**'
      - '.github/workflows/build-airflow.yml'
  workflow_dispatch:
    inputs:
      publish_version:
        description: 'Also publish a version tag (v1, v2, ...)'
        required: true
        default: false
        type: boolean

jobs:
  build:
    uses: ./.github/workflows/_build-container-dev.yml
    with:
      image_name: airflow
      context: ./airflow-image
      dockerfile: ./airflow-image/Dockerfile.airflow
    secrets: inherit
