name: Build and Push Airflow Image

on:
  push:
    paths:
      - 'airflow-image/**'
      - '.github/workflows/build-airflow.yml'
  workflow_dispatch:
    inputs:
      dev_mode:
        description: 'Build as dev image only (dev tag) even on the main branch'
        required: false
        default: false
        type: boolean

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_build-container-dev.yml
    with:
      image_name: airflow
      context: ./airflow-image
      dockerfile: ./airflow-image/Dockerfile.airflow
      dev_mode: ${{ github.event_name == 'workflow_dispatch' && inputs.dev_mode }}
    secrets: inherit
