name: Build and Push GitHub Runner Image

on:
  push:
    paths:
      - 'github-runner/**'
      - '.github/workflows/build-github-runner.yml'
  workflow_dispatch:
    inputs:
      dev_mode:
        description: 'Build as dev image only (dev tag) even on the main branch'
        required: false
        default: false
        type: boolean

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_build-container-dev.yml
    with:
      image_name: github-runner
      context: ./github-runner
      dockerfile: ./github-runner/Dockerfile.github-runner
      dev_mode: ${{ github.event_name == 'workflow_dispatch' && inputs.dev_mode }}
    secrets: inherit
