name: Build and Push DNS Server Image

on:
  push:
    paths:
      - 'dns-server/**'
      - '.github/workflows/build-dns-server.yml'
  workflow_dispatch:
    inputs:
      publish_version:
        description: 'Also publish a version tag (v1, v2, ...)'
        required: true
        default: false
        type: boolean

jobs:
  build:
    uses: ./.github/workflows/_build-container-dev.yml
    with:
      image_name: dns-server
      context: ./dns-server
      dockerfile: ./dns-server/Dockerfile
    secrets: inherit
